In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
print(np.arange(10,51,2))
arr[arr%2==0]

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.00663454])

In [24]:
np.random.randn(25)

array([-1.26576122,  2.19691426, -0.01036422,  0.06053901, -0.73187856,
       -1.26690742, -0.11646163,  1.8304863 , -2.25964685, -1.03723122,
        0.22567136,  0.56387164,  1.3431139 , -0.90893159,  1.10948928,
       -0.06246552,  0.23170591, -0.75588787,  0.50443495, -0.1879425 ,
       -1.42674018,  0.62959981,  0.11953365, -1.30966483,  0.91558657])

In [28]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [30]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [38]:
mat[3,4]

20

In [40]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [41]:
mat[4]

array([21, 22, 23, 24, 25])

In [42]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
mat.sum()

325

In [72]:
print(np.std(mat))
np.sqrt(np.mean((mat-mat.mean())**2))

7.211102550927978


7.211102550927978

In [81]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [82]:
np.column_stack(mat).sum(axis=1)

array([55, 60, 65, 70, 75])

In [83]:
np.add(220,90)

310

In [84]:
np.subtract(20,90)

-70

In [85]:
np.matmul(mat,mat)

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [86]:
np.logaddexp(1,2)

2.313261687518223

In [87]:
np.log1p(mat)

array([[0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872],
       [2.83321334, 2.89037176, 2.94443898, 2.99573227, 3.04452244],
       [3.09104245, 3.13549422, 3.17805383, 3.21887582, 3.25809654]])

In [99]:
a = np.array([1+2j, 3+4j, 5+6j])
print(a.imag)
a

[2. 4. 6.]


array([1.+2.j, 3.+4.j, 5.+6.j])

In [102]:
np.divmod(mat,mat)

(array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]), array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]))

In [103]:
np.sign(mat)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [105]:
print(np.conj(a))
np.conjugate(a)

[1.-2.j 3.-4.j 5.-6.j]


array([1.-2.j, 3.-4.j, 5.-6.j])

In [106]:
np.reciprocal(mat)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [107]:
np.greater_equal(mat,mat)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [108]:
np.maximum(mat,mat)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
np.fmod(mat,mat)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])