In [ ]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(arr[6])
print(arr[1:6])
print(arr[4:])
print(arr[:8])

6
[1 2 3 4 5]
[ 4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7]


In [ ]:
arr[:6] = 100
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
arr[:]

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
slice_arr = arr[:5]
slice_arr

array([100, 100, 100, 100, 100])

In [ ]:
slice_arr[:4] = 200
print(slice_arr)
print(arr)

[200 200 200 200 100]
[200 200 200 200 100 100   6   7   8   9  10]


In [ ]:
arr_copy = arr.copy()
arr_copy

array([200, 200, 200, 200, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
arr_copy[:] = 100
print(arr_copy)
print(arr)

[100 100 100 100 100 100 100 100 100 100 100]
[200 200 200 200 100 100   6   7   8   9  10]


In [ ]:
arr_2d = np.array([[1,4,3],[35,66,22],[3,6,9]])
arr_2d

array([[ 1,  4,  3],
       [35, 66, 22],
       [ 3,  6,  9]])

In [ ]:
print(arr_2d[0][0])
print(arr_2d[0])
print(arr_2d[0][:2])
print(arr_2d[1][1])
print(arr_2d[2,2])
print(arr_2d[1,:2])
print(arr_2d[:2,1:])
print(arr_2d[:2,1])

1
[1 4 3]
[1 4]
66
9
[35 66]
[[ 4  3]
 [66 22]]
[ 4 66]


In [ ]:
bool_arr = arr > 100
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [ ]:
arr[bool_arr]

array([200, 200, 200, 200])

In [ ]:
arr[arr>150]

array([200, 200, 200, 200])

In [ ]:
arr_2dn = np.arange(50).reshape(5,10)
arr_2dn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2dn[1:3,3:5]

array([[13, 14],
       [23, 24]])