In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
import numpy as np
arr = np.array(my_list)
print(arr)   
arr

[1 2 3]


array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.arange(0,11))
print(np.arange(0,11,2))
np.arange(1,11,2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


array([1, 3, 5, 7, 9])

In [ ]:
print(np.zeros(5))
np.zeros((4,7))

[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
print(np.random.rand(10))
np.random.rand(5,6)

[0.25459585 0.29237729 0.01867768 0.91693815 0.61652077 0.94041389
 0.98803258 0.42913674 0.98882066 0.10911392]


array([[0.4620894 , 0.29905702, 0.53694686, 0.3352707 , 0.00340222,
        0.03834636],
       [0.34550525, 0.79998282, 0.74823326, 0.89131891, 0.24852361,
        0.80345511],
       [0.74318645, 0.86900575, 0.47250387, 0.33109558, 0.72926993,
        0.36522197],
       [0.50634135, 0.68088582, 0.68457507, 0.90652797, 0.34321689,
        0.91002672],
       [0.31699863, 0.85424418, 0.49010703, 0.62823221, 0.60394947,
        0.16348853]])

In [ ]:
np.random.randn(100)

array([ 0.19383826, -0.7009697 ,  0.99340426,  0.1813842 ,  1.40489585,
        1.05868737, -1.42828802,  0.3213308 ,  2.3325281 ,  0.90563482,
       -1.97119644, -0.49526584,  1.01051972,  0.17049809,  0.41065541,
       -1.04097321, -0.34474324, -0.10724172,  0.87652874,  1.17753269,
       -0.9359146 ,  1.02827349,  1.24668937,  1.30411257, -0.71254327,
        0.04996283, -0.5798432 ,  0.42497238, -0.19220682,  0.4735217 ,
        0.94862692,  0.61613261, -1.4877397 , -1.09620911, -0.34463557,
        0.83182283, -0.79835785, -0.67843775, -0.56675452, -0.4135528 ,
       -0.90713473,  0.89530662, -0.82024943,  1.17319319, -0.70207864,
       -0.41444507,  0.27872055,  1.29633972, -0.19516287, -2.20733982,
       -0.96406159, -0.00488903, -0.62611485, -0.85467592,  0.01981632,
       -0.15414615, -0.2372996 ,  0.50252823,  0.83587848, -1.45321941,
        0.18319724, -1.06479577,  2.12546535, -0.44058711, -0.9722195 ,
       -2.71415466,  0.31665722,  0.79079489,  0.99578408, -1.63

In [ ]:
print(np.random.randint(10,50,20))
np.random.randint(10,50)

[23 18 15 31 48 26 32 38 42 20 42 30 38 34 18 45 47 38 21 43]


25

In [ ]:
arr = np.arange(0,25)
ranarr = np.random.randint(0,25,10)

print(np.reshape(ranarr,(2,5)))
print(np.reshape(arr,25))

print(arr.reshape(5,5))
print(ranarr.reshape(2,5))

[[24  3 13 17 20]
 [15 14 19  1  6]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[24  3 13 17 20]
 [15 14 19  1  6]]


In [ ]:
print(np.max(arr))
print(np.min(ranarr))

print(arr.max())
print(ranarr.min())

24
0
24
0


In [ ]:
print(np.argmax(arr))
print(np.argmin(ranarr))

print(arr.argmax())
print(ranarr.argmin())

24
8
24
8


In [ ]:
print(arr.shape)
ranarr.shape

(25,)


(10,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint
randint(3,10,2)

array([7, 3])