In [ ]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2 = np.arange(0,21,2)
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
print(arr+arr2)
print(arr-arr2)
print(arr*arr2)
print(arr/arr2)

[ 0  3  6  9 12 15 18 21 24 27 30]
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
[  0   2   8  18  32  50  72  98 128 162 200]
[nan 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [ ]:
print(arr+3)
print(arr-4)
print(arr*4)
print(arr/2)
print(arr**2)
print(arr**arr2)

[ 3  4  5  6  7  8  9 10 11 12 13]
[-4 -3 -2 -1  0  1  2  3  4  5  6]
[ 0  4  8 12 16 20 24 28 32 36 40]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  0   1   4   9  16  25  36  49  64  81 100]
[                  1                   1                  16
                 729               65536             9765625
          2176782336        678223072849     281474976710656
  150094635296999121 7766279631452241920]


In [ ]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.max(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10


In [ ]:
print(np.sin(arr))
print(np.tan(arr))
print(np.arcsin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         1.57079633        nan        nan        nan        nan
        nan        nan        nan        nan        nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in arcsin
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
print(np.log(arr))
print(np.log10(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251 1.        ]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  


// for more univeral functions, see the documentation of numpy for universal functions
https://numpy.org/doc/stable/reference/ufuncs.html

